config/routes.rb
RailsinstallerDemo::Application.routes.draw do

  
  resources :tv_episodes, :tv_seasons, :genres, :ratings, :tv_shows, :reviews

  get "welcome/graphs"

  match "about" => "welcome#about"
  match "index" => "welcome#index"
  match "stats" => "welcome#stats"
  match "tv_show_search" => "welcome#tv_show_search"
  match "tv_episode_search" => "welcome#tv_episode_search"
  match "review_search" => "welcome#review_search"
  match "search_results" => "welcome#search_results"
  match "graphs" => "welcome#graphs"
  match "genres_graphs" => "welcome#genres_graphs"

   root :to => 'welcome#index.html'

end

app/models/tv_show.rb
class TvShow < ActiveRecord::Base
	attr_accessible :year_released, :year_ended, :title, :description, :id

	has_many :genres, :dependent => :destroy
	has_many :ratings, :as => :rateable, :dependent => :destroy
	has_many :reviews, :as => :reviewable, :dependent => :destroy
	has_many :tv_seasons, :dependent => :destroy
	has_many :tv_episodes, :through => :tv_seasons, :dependent => :destroy

	validates :title, :year_released, :presence => { :message => "This field is required."}
	validates :title, :length => { :minimum => 2 }

  def self.total_grouped_by_day(start)
    tv_shows = unscoped.where(year_released: start.beginning_of_day..Time.zone.now).group("date(year_released)")
    tv_shows = tv_shows.select("date(year_released) as year_released, count(*) as count")
  	tv_shows.each_with_object({}) do |tv_show, counts|
  	    counts[tv_show.year_released.to_date.strftime("%Y")] = tv_show.count
  	end
  end
  def IMDB_rating(id)
    show = Rating.where(:rateable_type=>'TvShow',:rating_website=>'iMDB',:rateable_id=>id)
  end
  def self.find_title(title,year)
    TvShow.where(:title=>title,:year_released=>year)
  end
  def self.seasons(id)
    TvSeason.where(:tv_show_id=>id).select('id as tv_season_id, number')
  end
  def self.episodes(id,order,limit)

  end
  def self.reviews(id)
    Review.where(:reviewable_id=>id,:reviewable_type=>'TvShow')
  end
  def self.parseIMDB
      puts "parsing tv shows"
      require_relative '../../script/parse_shows_prod'
  end
  def self.simple_search(search)
	  if search
	    where 'UPPER(title) LIKE UPPER(?) or UPPER(description) LIKE UPPER(?)', "%#{search}%", "%#{search}%"
	  else
	    scoped
	  end
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  # GET /tv_shows
  # GET /tv_shows.json
  def index
    @tv_shows = TvShow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: TVShowsDatatable.new(view_context) }
    end
  end

  # GET /tv_shows/1
  # GET /tv_shows/1.json
  def show
    @tv_show = TvShow.find(params[:id])
    @IMDBrating = Rating.rating("TvShow","tv_shows",params[:id],'IMDB').to_a[0]
    @TVDBrating = Rating.rating("TvShow","tv_shows",params[:id],'TVDB').to_a[0]

    if !@IMDBrating.average.nil?
      @IMDBrating = @IMDBrating.average[0..2]
    else
      @IMDBrating = "N/A"
    end

    if !@TVDBrating.average.nil?
      @TVDBrating = @TVDBrating.average[0..2]
    else
      @TVDBrating = "N/A"
    end

    require 'open-uri'
    require 'uri'
    require 'json'
    result = JSON.parse(open("http://imdbapi.org/?title="+URI.escape(@tv_show.title.to_s)+"&type=json&plot=simple&episode=0&limit=1&year="+@tv_show.year_released.try(:strftime, "%Y")+"&yg=1&mt=TVS&lang=en-US&offset=&aka=simple&release=simple&business=0&tech=0").read)

    if !result[0].nil?
      @poster = result[0]["poster"]
      @description = result[0]["plot_simple"]
      @IMDBurl = result[0]["imdb_url"].strip
      @actors = result[0]["actors"]
    end

    @reviews = TvShow.reviews(@tv_show.id)
    @seasonCount = TvSeason.where(:tv_show_id => @tv_show.id).count
    @epCount = 0
    @tv_show.tv_seasons.each do |s|
      @reviews = @reviews + s.reviews(s.id)
      s.tv_episodes.each do |e|
        @epCount = @epCount + 1
        @reviews = @reviews + e.reviews(e.id)
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tv_show }
    end
  end

  # GET /tv_shows/new
  # GET /tv_shows/new.json
  def new
    @tv_show = TvShow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tv_show }
    end
  end

  # GET /tv_shows/1/edit
  def edit
    @tv_show = TvShow.find(params[:id])
  end

  # POST /tv_shows
  # POST /tv_shows.json
  def create
    @tv_show = TvShow.new(params[:tv_show])

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully created.' }
        format.json { render json: @tv_show, status: :created, location: @tv_show }
      else
        format.html { render action: "new" }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tv_shows/1
  # PUT /tv_shows/1.json
  def update
    @tv_show = TvShow.find(params[:id])

    respond_to do |format|
      if @tv_show.update_attributes(params[:tv_show])
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1
  # DELETE /tv_shows/1.json
  def destroy
    @tv_show = TvShow.find(params[:id])
    @tv_show.destroy

    respond_to do |format|
      format.html { redirect_to tv_shows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
  def shows_ratings_data(id)
  	arr = Array.new 
    seasons = TvShow.seasons(id)
    seasons.each do |season|
      episodes = TvSeason.episodes(season.tv_season_id)
      episodes.each do |episode|
        arr.push("S"+season.number.to_s+"xE"+episode.number.to_s)
        arr.push(Rating.where("rateable_type = 'TvEpisode' and rating_website = 'IMDB' and rateable_id = ?", episode.tv_episode_id).average("total_rating") || nil)
        arr.push(Rating.where("rateable_type = 'TvEpisode' and rating_website = 'TVDB' and rateable_id = ?", episode.tv_episode_id).average("total_rating") || nil)
        arr.push(episode.title)
        arr.push(episode.tv_episode_id)
      end
    end

    arr.each_slice(5).map do |num,rating,rating_TVDB,title,id|
      {
        year: num,
        average: rating || nil,
        average_TVDB: rating_TVDB || nil,
        title: title,
        id: id
      }
    end
  end
end

app/views/tv_shows/_form.html.erb
<%= simple_form_for(@tv_show) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :year_released, as: :date, start_year: Date.today.year,
                              end_year: Date.today.year-100, discard_day:true, discard_month:true,
                              order: [:year] %>
    <%= f.input :year_ended, as: :date, start_year: Date.today.year,
                              end_year: Date.today.year-100, discard_day:true, discard_month:true,
                              order: [:year], :include_blank => "Has not ended", :priority => "Has not ended",
                              hint: '(Leave blank if show has not ended)'  %>
    <%= f.input :description, :input_html => {:rows => 5, :class => "span6"} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<h3>Edit tv show</h3>

<%= render 'form' %>

<%= link_to 'Show', @tv_show %> |
<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/index.html.erb
<% content_for :javascript do %>
<script>
</script>
<% end %>

<h3>TV Show Index</h3>

<table cellpadding="0" cellspacing="0" border="0" id="tvshows" class="datatable table table-striped table-bordered" data-source="<%= tv_shows_url(format: "json") %>">
<thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th class="medium">Year Released</th>
    <th class="medium">Year Ended</th>
    <th class="actions">Actions</th>
  </tr>
</thead>
<tbody>
</tbody>
</table>

<br />

<%= button_to "Add TV show", new_tv_show_path, :method => "get", :class=> "btn btn-primary"%>

app/views/tv_shows/new.html.erb
<h3>New tv show</h3>

<%= render 'form' %>

<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/show.html.erb
<% content_for :javascript do %>
<script>
$(function() {
  Morris.Line({
    element: 'shows_ratings',
    data: $('#shows_ratings').data('tv-shows'),
    xkey: 'year',
    ykeys: ['average','average_TVDB'],
    labels: ['Average Episode Rating', 'Average Ep rating TVDB'],
    pointSize: 0,
    parseTime: false,
    continuousLine:false,
    hideHover: true,
    hoverCallback: function (index, options) {
      var row = options.data[index];
      return "<b>"+row.year + "</b><br> IMDB Average: <span style='color:#F89406'>" 
      + row.average + "</span><br>TVDB Average: <span style='color:#468847'>"+row.average_TVDB+"</span><br>" + "<a href='../tv_episodes/"+row.id+"'>"+row.title+"</a>";
    },
    lineColors: ['#F89406','#468847'],
    lineWidth: 2
  });
});
</script>
<% end %>

<div class="page-header" style="margin:0px">
  <h1>
    <%= link_to @tv_show.title, @tv_show%>
    <small>
      (<%= @tv_show.year_released.try(:strftime, "%Y") %>
      -
      <%= @tv_show.year_ended.try(:strftime, "%Y") %>)</small>
    <span class="badge badge-warning rating-badge pull-right" style="margin-left:10px">
      <a class="white_link" href=<%= @IMDBurl %>>IMDB <%= @IMDBrating %></a>
      </span>
      <span class="badge badge-success rating-badge pull-right" style="margin-left:10px">
      TVDB <%= @TVDBrating %>
      </span>
  </h1>
</div>
    <div class="row-fluid">
      <div class="span3" style="width:17%">
        <% if !@poster.nil? %>
          <img src=<%= @poster %> style="margin-bottom:20px"/>
        <% end %>
        <%= button_to "Edit", edit_tv_show_path(@tv_show), :method => "get",:class=> "btn btn-primary inline"%>
        <%= button_to "TV Show Index", tv_shows_path, :method => "get",:class=> "btn btn-primary inline"%>
      </div>
      <div class="span6">
        <div class="tabbable">
          <ul class="nav nav-tabs" id="myTab">
            <li class="active">
              <a data-toggle="tab" href="#about">About</a>
            </li>
            <li>
              <a data-toggle="tab" href="#tvreviews">Reviews</a>
            </li>
          </ul>

          <div class="tab-content" style="overflow:hidden">
            <div class="tab-pane active" id="about">
              <%= @seasonCount %> seasons, <%= @epCount %> episodes<br><br>
              <p><b>Genres:</b>
                  <% @tv_show.genres.each do |genre| %>
                  <span class="badge badge-info">
                    <%= genre.name %></span>
              <% end %></p>
              <p><b>Description: </b><%= @description %></p>
              <p><b>Actors: </b>            
               <% if !@actors.nil? and @actors.count > 0 %>
                <% @actors.each do |actor| %>
                  <%= actor %><% if actor != @actors.last %>, <% end %>
                <% end %>
              <% end %>
              <%= content_tag :div, "", id: "shows_ratings", style: "height:190px", data: {tv_shows: shows_ratings_data(@tv_show.id)} %>
            </div>
            <div class="tab-pane" id="tvreviews">
             <% if !@reviews.nil? and @reviews.count > 0 %>
              <% @reviews.each do |review| %>
                <h6><%= link_to review.reviewable.tv_season.tv_show.title.to_s+": "+review.title, review %> <small>
             by <%= review.author %> at <%= link_to review.website, review.link %></small>
          <span class="pull-right"><%= review.year_reviewed.try(:strftime, "%m/%d/%y") %>
          &nbsp;          <% if review.positives-review.negatives == 0 %>
            <span class="badge badge-warning">
          <% elsif review.positives-review.negatives > 0 %>
            <span class="badge badge-success">+
          <% else %>          
            <span class="badge badge-important">
          <% end %><%= review.positives-review.negatives %><span/>
          </span></h6>
        </span></h6>
                <br>
                <%= review.content[0..300]+"..." %><%= link_to 'Read full review', review_path(review) %>
             <% end %>
            <% else %>
              There are no reviews yet.
            <% end %>
            </div>
          </div>

            </div>
          </div>
        <div class="span4" style="width:29%">
          <div class="accordion" id="accordion1">
            <% @tv_show.tv_seasons.each do |season| %>
            <div class="accordion-group">
              <div class="accordion-heading">
                <%= link_to '<i class="icon-plus"></i>'.html_safe, tv_season_path(season.id), :style => 'display:inline', :class => 'accordion-toggle', :data => {:toggle=>"collapse",:parent=>"#accordian1"}, :href => '#'+season.id.to_s %>
                <%= link_to 'Season '+ season.number.to_s, tv_season_path(season.id) %>
              </div>
              <div id=<%= season.id.to_s %>
                class="accordion-body collapse">
                <div class="accordion-inner">
                  <ul>
                    <% season.tv_episodes.each do |episode| %>
                    <li>
                      <%= link_to '#'+ episode.number.to_s+': '+episode.title, tv_episode_path(episode.id) %></li>
                    <% end %></ul>
                </div>
              </div>
            </div>
            <% end %>
        </div>
      </div></div>