config/routes.rb
RailsinstallerDemo::Application.routes.draw do

  
  resources :tv_episodes, :tv_seasons, :genres, :ratings, :tv_shows, :reviews

  get "welcome/graphs"

  match "about" => "welcome#about"
  match "index" => "welcome#index"
  match "stats" => "welcome#stats"
  match "tv_show_search" => "welcome#tv_show_search"
  match "tv_episode_search" => "welcome#tv_episode_search"
  match "review_search" => "welcome#review_search"
  match "search_results" => "welcome#search_results"
  match "graphs" => "welcome#graphs"
  match "genres_graphs" => "welcome#genres_graphs"

   root :to => 'welcome#index.html'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: ReviewsDatatable.new(view_context) }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])
    @positive = ((@review.positives / 1.0 / @review.content.split.size) * 100).round(2)
    @negative = ((@review.negatives / 1.0 / @review.content.split.size) * 100).round(2)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content, :input_html => {:rows => 5, :class => "span6"} %>
    <%= f.input :year_reviewed, as: :date, start_year: Date.today.year,
                              end_year: Date.today.year-100,
                              order: [:day, :month, :year], :include_blank => "", :priority => "" %>
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :link %>
    <%= f.input :rating %>
    <%= f.input :website %>
    <%= f.input :reviewable_type, collection: ["TvShow", "TvSeason", "TvEpisode"], :include_blank => false %>
    <%= f.input :reviewable_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save', class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<% content_for :javascript do %>
<script>
</script>
<% end %>

<h3>Review Index</h3>

<table cellpadding="0" cellspacing="0" border="0" id="reviews" class="datatable table table-striped table-bordered" data-source="<%= reviews_url(format: "json") %>">
<thead>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Author</th>
    <th>Website</th>
    <th class="actions">Actions</th>
  </tr>
</thead>
<tbody>
</tbody>
</table>

<br />

<%= button_to "Add Review", new_review_path, :method => "get", :class=> "btn btn-primary"%>

app/views/reviews/new.html.erb
<h3>New review</h3>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<div class="page-header" style="margin:0px">
  <h1>
    <%= link_to @review.title, @review %>
    <small>
      (<%= @review.year_reviewed.try(:strftime, "%B %d, %Y") %>) </small>
      <span class="pull-right" style="line-height:38px;font-size:18px;">
      <span class="badge badge-success"><%= @review.positives %> positive words</span>
      - <span class="badge badge-important"><%= @review.negatives %> negative words</span>
          = <% if @review.positives-@review.negatives == 0 %>
          <span class="badge badge-warning">
          <% elsif @review.positives-@review.negatives > 0 %>
           <span class="badge badge-success">+
          <% else %>          
          <span class="badge badge-important">
          <% end %><%= @review.positives-@review.negatives %><span/></span>
          </span>
      <%= @IMDBrating %>
      </span>
  </h1>
</div>

<div class="row-fluid">
  <div class="span2">

<p>
  <b>Author:</b><br>
  <%= @review.author %>
</p>

<p>
  <b>Rating:</b><br>
  <%= @review.rating %>
</p>

<p>
  <b>Website:</b><br>
  <a href=<%= @review.link %>><%= @review.website %></a>
</p>

<p>
  <b>Sentiments:</b><br>
  <%= @review.content.split.size %> words<br><br>
  <span style="color:#468847"><%= @positive %>% of the words are positive</span><br><br>
  <span style="color:#B94A48"><%= @negative %>% of the words are negative</span>
</p>

<p>  
  <b>Reviewed:</b><br>
  <% if @review.reviewable_type == 'TvShow' %>
    <%= link_to @review.reviewable.title, tv_show_path(@review.reviewable) %>
  <% elsif @review.reviewable_type == 'TvSeason' %>
    <%= link_to @review.reviewable.number, tv_season_path(@review.reviewable) %>
  <% elsif @review.reviewable_type == 'TvEpisode' %>
    <%= link_to @review.reviewable.tv_season.tv_show.title, tv_show_path(@review.reviewable.tv_season.tv_show) %>: 
    <%= link_to @review.reviewable.title, tv_episode_path(@review.reviewable) %>
  <% end %>
</p>
<p>  
  <b>Review type:</b><br>
  <% if @review.reviewable_type == 'TvShow' %>TV Show
  <% elsif @review.reviewable_type == 'TvSeason' %>TV Season
  <% elsif @review.reviewable_type == 'TvEpisode' %>TV Episode
  <% end %>
</p>
<%= button_to "Edit", edit_review_path(@review), :method => "get",:class=> "btn btn-primary inline"%>
<%= button_to "Review Index", reviews_path, :method => "get",:class=> "btn btn-primary inline"%>
</div>

<div class="span10" id="review_content">
  <pre><%= @review.content %></pre>
</div>

</div>