config/routes.rb
RailsinstallerDemo::Application.routes.draw do

  
  resources :tv_episodes, :tv_seasons, :genres, :ratings, :tv_shows, :reviews

  get "welcome/graphs"

  match "about" => "welcome#about"
  match "index" => "welcome#index"
  match "stats" => "welcome#stats"
  match "tv_show_search" => "welcome#tv_show_search"
  match "tv_episode_search" => "welcome#tv_episode_search"
  match "review_search" => "welcome#review_search"
  match "search_results" => "welcome#search_results"
  match "graphs" => "welcome#graphs"
  match "genres_graphs" => "welcome#genres_graphs"

   root :to => 'welcome#index.html'

end

app/models/tv_episode.rb
class TvEpisode < ActiveRecord::Base
	attr_accessible :air_date, :tv_season_id, :number, :title

	has_many :ratings, :as => :rateable, :dependent => :destroy
	has_many :reviews, :as => :reviewable, :dependent => :destroy
	has_many :genres, :through => :tv_season
	
	belongs_to :tv_season
	belongs_to :tv_show

	validates :tv_season_id, :number, :presence => { :message => "This field is required." }
	validates :number, :numericality => { :only_integer => true, :message => "Number must be an integer." }

	default_scope :order => "number ASC"

	def self.total_grouped_by_day(start)
	    tv_episodes = unscoped.where(air_date: start.beginning_of_day..Time.zone.now)
	    tv_episodes = tv_episodes.group("date(air_date)")
	    tv_episodes = tv_episodes.select("date(air_date) as air_date, count(*) as count")
		tv_episodes.each_with_object({}) do |tv_episode, counts|
		    counts[tv_episode.air_date.to_date.strftime("%Y")] = tv_episode.count
		end
    end
    def self.reviews(id)
  	  Review.where(:reviewable_id=>id,:reviewable_type=>'TvEpisode')
 	end
    def rating(id)
    	Rating.where(:rateable_id=>id,:rateable_type=>'TvEpisode')
    end
    def reviews(id)
    	reviews = Review.where(:reviewable_id=>id,:reviewable_type=>'TvEpisode')
    end
    def self.simple_search(search)
	  if search
	    where 'UPPER(title) LIKE UPPER(?)', "%#{search}%"
	  else
	    scoped
	  end
  end
end

app/controllers/tv_episodes_controller.rb
class TvEpisodesController < ApplicationController
  # GET /tv_episodes
  # GET /tv_episodes.json
  def index
    @tv_episodes = TvEpisode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json:  TVEpisodesDatatable.new(view_context) }
    end
  end

  # GET /tv_episodes/1
  # GET /tv_episodes/1.json
  def show
    @tv_episode = TvEpisode.find(params[:id])
    @IMDBrating = Rating.rating("TvEpisode","tv_episodes",params[:id],'IMDB').to_a[0]
    @TVDBrating = Rating.rating("TvEpisode","tv_episodes",params[:id],'TVDB').to_a[0]


    if !@IMDBrating.average.nil?
      @IMDBrating = @IMDBrating.average[0..2]
    else
      @IMDBrating = "N/A"
    end

    if !@TVDBrating.average.nil?
      @TVDBrating = @TVDBrating.average[0..2]
    else
      @TVDBrating = "N/A"
    end

    @reviews = TvEpisode.reviews(@tv_episode.id)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tv_episode }
    end
  end

  # GET /tv_episodes/new
  # GET /tv_episodes/new.json
  def new
    @tv_episode = TvEpisode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tv_episode }
    end
  end

  # GET /tv_episodes/1/edit
  def edit
    @tv_episode = TvEpisode.find(params[:id])
  end

  # POST /tv_episodes
  # POST /tv_episodes.json
  def create
    @tv_episode = TvEpisode.new(params[:tv_episode])

    respond_to do |format|
      if @tv_episode.save
        format.html { redirect_to @tv_episode, notice: 'Tv episode was successfully created.' }
        format.json { render json: @tv_episode, status: :created, location: @tv_episode }
      else
        format.html { render action: "new" }
        format.json { render json: @tv_episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tv_episodes/1
  # PUT /tv_episodes/1.json
  def update
    @tv_episode = TvEpisode.find(params[:id])

    respond_to do |format|
      if @tv_episode.update_attributes(params[:tv_episode])
        format.html { redirect_to @tv_episode, notice: 'Tv episode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tv_episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_episodes/1
  # DELETE /tv_episodes/1.json
  def destroy
    @tv_episode = TvEpisode.find(params[:id])
    @tv_episode.destroy

    respond_to do |format|
      format.html { redirect_to tv_episodes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tv_episodes_helper.rb
module TvEpisodesHelper
end

app/views/tv_episodes/_form.html.erb
<%= simple_form_for(@tv_episode) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :title %>
    <%= f.input :air_date,  as: :date, start_year: Date.today.year,
                              end_year: Date.today.year-100,
                              order: [:day, :month, :year], :include_blank => "", :priority => "" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tv_episodes/edit.html.erb
<h3>Edit tv episode</h3>

<%= render 'form' %>

<%= link_to 'Show', @tv_episode %> |
<%= link_to 'Back', tv_episodes_path %>

app/views/tv_episodes/index.html.erb
<% content_for :javascript do %>
<script>
</script>
<% end %>

<h3>TV Episode Index</h3>

<table cellpadding="0" cellspacing="0" border="0" id="tvepisodes" class="datatable table table-striped table-bordered" data-source="<%= tv_episodes_url(format: "json") %>">
<thead>
  <tr>
    <th>Title</th>
    <th>Show</th>
    <th class="short">Season</th>
    <th class="short">Number</th>
    <th class="medium">Air Date</th>
    <th class="actions">Actions</th>
  </tr>
</thead>
<tbody>
</tbody>
</table>

<br />

<%= button_to "Add TV episode", new_tv_episode_path, :method => "get", :class=> "btn btn-primary"%>

app/views/tv_episodes/new.html.erb
<h3>New tv episode</h3>

<%= render 'form' %>

<%= link_to 'Back', tv_episodes_path %>

app/views/tv_episodes/show.html.erb
<div class="page-header" style="margin:0px">
    <h1>  <%= link_to @tv_episode.title, @tv_episode %>
      <small> 
        <%= link_to @tv_episode.tv_season.tv_show.title, @tv_episode.tv_season.tv_show, :method => "get" %>
        <%= link_to 'S'+@tv_episode.tv_season.number.to_s, @tv_episode.tv_season %>x<%= link_to 'E'+@tv_episode.number.to_s, @tv_episode %> (<%= @tv_episode.air_date.try(:strftime, "%Y") %>)
      </small>
    <span class="badge badge-warning rating-badge pull-right" style="margin-left:10px">
      IMDB <%= @IMDBrating %>
      </span>
      <span class="badge badge-success rating-badge pull-right" style="margin-left:10px">
      TVDB <%= @TVDBrating %>
      </span>
    </h1>
</div>

    <div class="row-fluid">
      <div class="span8">
        <div class="tabbable">
          <ul class="nav nav-tabs" id="myTab">
            <li class="active">
              <a data-toggle="tab" href="#about">About</a>
            </li>
            <li>
              <a data-toggle="tab" href="#tvreviews">Reviews</a>
            </li>
          </ul>

          <div class="tab-content">
            <div class="tab-pane active" id="about"><%= @tv_episode.description %>
              </div>
              <div class="tab-pane" id="tvreviews">
               <% if !@reviews.nil? and @reviews.count > 0 %>
                <% @reviews.each do |review| %>
                <h6>
            <%= link_to review.reviewable.tv_season.tv_show.title.to_s+": "+review.title, review %> <small>
             by <%= review.author %> at <%= link_to review.website, review.link %></small>
          <span class="pull-right"><%= review.year_reviewed.try(:strftime, "%m/%d/%y") %>
          &nbsp;<span class="badge badge-success">+2<span/></span></h6>
                  <%= review.content[0..300]+"..." %><%= link_to 'Read full review', review_path(review) %>
                  <br><br>
               <% end %>
              <% else %>
                There are no reviews yet.
              <% end %>
              </div>
            <br>
            <%= link_to 'Edit', edit_tv_episode_path(@tv_episode) %> |
            <%= link_to 'TV Episodes Index', tv_episodes_path %>
          </div>
        </div>
      </div>
        <div class="span4">
          <div class="accordion" id="accordion1">
            <% @tv_episode.tv_season.tv_show.tv_seasons.each do |season| %>
            <div class="accordion-group">
              <div class="accordion-heading">
                <%= link_to '<i class="icon-plus"></i>'.html_safe, tv_season_path(season.id), :style => 'display:inline', :class => 'accordion-toggle', :data => {:toggle=>"collapse",:parent=>"#accordian1"}, :href => '#'+season.id.to_s %>
                <%= link_to 'Season '+ season.number.to_s, tv_season_path(season.id) %>
              </div>
              <div id=<%= season.id.to_s %>
                class="accordion-body collapse">
                <div class="accordion-inner">
                  <ul>
                    <% season.tv_episodes.each do |episode| %>
                    <li>
                      <%= link_to '#'+ episode.number.to_s+': '+episode.title, tv_episode_path(episode.id) %></li>
                    <% end %></ul>
                </div>
              </div>
            </div>
            <% end %></div>
        </div>
      </div>