config/routes.rb
RailsinstallerDemo::Application.routes.draw do

  
  resources :tv_episodes, :tv_seasons, :genres, :ratings, :tv_shows, :reviews

  get "welcome/graphs"

  match "about" => "welcome#about"
  match "index" => "welcome#index"
  match "stats" => "welcome#stats"
  match "tv_show_search" => "welcome#tv_show_search"
  match "tv_episode_search" => "welcome#tv_episode_search"
  match "review_search" => "welcome#review_search"
  match "search_results" => "welcome#search_results"
  match "graphs" => "welcome#graphs"
  match "genres_graphs" => "welcome#genres_graphs"

   root :to => 'welcome#index.html'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "TV Ratings & Reviews", root_path, :class => 'brand' %>
<ul class="nav">
  <li><a href="../about">About</a></li>
     <li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">
Stats
<b class="caret"></b>
</a>
<ul class="dropdown-menu">
  <li><%= link_to "Overall", "../stats" %></li>
  <li><%= link_to "Ratings & Reviews Graphs", "../graphs"%></li>  
  <li><%= link_to "Genres Graphs", "../genres_graphs"%></li>  
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">
Lists
<b class="caret"></b>
</a>
<ul class="dropdown-menu">
  <li><%= link_to "Shows", tv_shows_path %></li>
  <li><%= link_to "Seasons", tv_seasons_path %></li>
  <li><%= link_to "Episodes", tv_episodes_path %></li>
  <li><%= link_to "Genres", genres_path %></li>
  <li><%= link_to "Ratings", ratings_path %></li>
  <li><%= link_to "Reviews", reviews_path %></li>
</ul>
</li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">
Advanced Search
<b class="caret"></b>
</a>
<ul class="dropdown-menu">
  <li><a href="../tv_show_search">TV shows</a></li>
  <li><a href="../tv_episode_search">TV episodes</a></li>
  <li><a href="../review_search">Reviews</a></li>
</ul>
</li>
</ul>
<div class="pull-right">
  <%= form_tag search_results_path, :method => 'get', :style => 'margin-bottom:0;margin-left:20px', :class => 'form-search' do %>
  <p style="margin-bottom:0">
    <%= text_field_tag :search, params[:search], :style => 'margin-top:5px', :class => 'input-long search-query', :placeholder => 'Search shows, episodes' %>
  </p>
<% end %>
</div>

app/views/layouts/_reviews.html.erb
<% for review in @recentReviews %>
  <div class="recentReviews">
        <div class="page-header" style="margin:0px">
          <h6>
          	<%= link_to review.reviewable.tv_season.tv_show.title.to_s+": "+review.title, review %> <small>
          	 by <%= review.author %> at <%= link_to review.website, review.link %></small>
          <span class="pull-right"><%= review.year_reviewed.try(:strftime, "%m/%d/%y") %>
          &nbsp;
          <% if review.positives-review.negatives == 0 %>
            <span class="badge badge-warning">
          <% elsif review.positives-review.negatives > 0 %>
            <span class="badge badge-success">+
          <% else %>          
            <span class="badge badge-important">
          <% end %><%= review.positives-review.negatives %><span/>
          </span></h6>
        </div>
        <%= review.content[0..300]+"..." %><%= link_to 'Read full review', review %>
  </div>
<% end %>

<%= will_paginate @recentReviews %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TV Ratings & Reviews" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <%= yield :javascript %>
    <script type="text/javascript">
      $('.dropdown-toggle').dropdown();
    </script>
  </body>
</html>